# cargo                                                             :Scratch:

# [[file:~/Workspace/Programming/rust-libs/lbfgs/lbfgs.note::*cargo][cargo:1]]
[package]
name = "lbfgs"
edition = "2018"
version = "0.0.8"
authors = ["Wenping Guo <ybyygu@gmail.com>"]

[dependencies]
quicli = "*"
libc = "*"
# cargo:1 ends here
