# cargo                                                             :Scratch:

# [[file:~/Workspace/Programming/rust-libs/lbfgs/lbfgs.note::*cargo][cargo:1]]
[package]
name = "lbfgs"
edition = "2018"
version = "0.0.14"
authors = ["Wenping Guo <ybyygu@gmail.com>"]

[dependencies]
quicli = "0.4"
vecfx = {git = "https://github.com/ybyygu/vecfx.git"}

[dev-dependencies]
approx = "0.3"
criterion = "0.2"

[[bench]]
name = "rosenbrock"
harness = false
# cargo:1 ends here
