# cargo                                                             :Scratch:

# [[file:~/Workspace/Programming/rust-libs/lbfgs/lbfgs.note::*cargo][cargo:1]]
[package]
name = "lbfgs"
edition = "2018"
version = "0.0.9"
authors = ["Wenping Guo <ybyygu@gmail.com>"]

[dependencies]
quicli = "0.4"
libc = "*"

[dev-dependencies]
approx = "0.3"
# cargo:1 ends here
